[package]
name = "enums"
version = "0.1.0"
edition = "2021"
authors = ["humyna <hufo125#gmail.com"]
date = "2022-04-06"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
